name: Build and Release run-node

on:
  push:
    branches: [ master ]   # "on checkin"

permissions:
  contents: write         # needed for creating release + uploading assets
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}/run-node

jobs:
  # ------------------------------------------------------------
  # Step 0: Create Release with incremented tag
  # ------------------------------------------------------------
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
      tag_name: ${{ steps.bump_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest=$latest_tag" >> $GITHUB_OUTPUT

      - name: Bump Tag
        id: bump_tag
        run: |
          old="${{ steps.get_tag.outputs.latest }}"
          base="${old#v}"
          IFS='.' read -r major minor patch <<< "$base"
          patch=$((patch+1))
          new="v$major.$minor.$patch"
          echo "tag=$new" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ steps.bump_tag.outputs.tag }}
          git push origin ${{ steps.bump_tag.outputs.tag }}

      - name: Create GitHub Release
        id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_tag.outputs.tag }}
          release_name: Release ${{ steps.bump_tag.outputs.tag }}
          draft: false
          prerelease: false

  # ------------------------------------------------------------
  # Step 1: Build & push builder images
  # ------------------------------------------------------------
  build-builder-images:
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22.04, 24.04]

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image names
        id: vars
        run: |
          echo "IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}:${{ matrix.version }}" >> $GITHUB_OUTPUT
          echo "CACHE=${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}:${{ matrix.version }}-cache" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - name: Build & Push builder image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/Dockerfile.ubuntu${{ matrix.version }}
          push: true
          tags: ${{ steps.vars.outputs.IMAGE }}
          cache-from: type=registry,ref=${{ steps.vars.outputs.CACHE }}
          cache-to: type=registry,ref=${{ steps.vars.outputs.CACHE }},mode=max

  # ------------------------------------------------------------
  # Step 2: Compile binaries
  # ------------------------------------------------------------
  build-multi-docker:
    needs: build-builder-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22.04, 24.04]

    steps:
      - uses: actions/checkout@v4

      - name: Build binary for Ubuntu ${{ matrix.version }}
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}:${{ matrix.version }}
          docker pull $IMAGE
          docker run --rm -v $(pwd):/src -w /src $IMAGE \
            bash -c "./build.sh && cp ./.build/run-node run-node-ubuntu${{ matrix.version }}"

      - uses: actions/upload-artifact@v4
        with:
          name: run-node-binaries-${{ matrix.version }}
          path: run-node-ubuntu${{ matrix.version }}
          retention-days: 5

  # ------------------------------------------------------------
  # Step 3: Attach binaries to the Release
  # ------------------------------------------------------------
  release-assets:
    needs: [create-release, build-multi-docker]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22.04, 24.04]

    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: run-node-binaries-${{ matrix.version }}
          path: ./release-bin

      - name: Upload ${{ matrix.version }} asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./release-bin/run-node-ubuntu${{ matrix.version }}
          asset_name: run-node-ubuntu${{ matrix.version }}
          asset_content_type: application/octet-stream